language: c

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
            - zlib1g-dev
            - sqlite3
            - libsqlite3-dev
            - check
            - libsubunit-dev
    - os: osx
      before_install:
        - brew install check

compiler: gcc

script:
  - make test