# This file will be deprecated shortly, please use the Makefile in 
# the root file.

all: $(O_FILES)
	@echo This src/Makefile will be deprecated shortly.
	@echo Please use the Makefile in the root project file.
	@cd .. && $(MAKE)
	
clean:
	@echo This src/Makefile will be deprecated shortly.
	@echo Please use the Makefile in the root project file.
	@cd .. && $(MAKE) clean
